# 产出构建产物，方便后续依赖跳过构建步骤
name: release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "^1.23.0"
      - id: get-version
        run: |
          echo "version=$(echo ${{github.ref}} | cut -c2-)" >> $GITHUB_OUTPUT
      - name: Build tool
        id: build
        run: |
          GOOS=linux GOARCH=amd64 go build -o pojt
          tar -zcvf "pojt-${{ steps.get-version.outputs.version }}-linux-amd64.tar.gz" pojt
          GOOS=linux GOARCH=386 go build -o pojt
          tar -zcvf "pojt-${{ steps.get-version.outputs.version }}-linux-i386.tar.gz" pojt
          GOOS=linux GOARCH=arm64 go build -o pojt
          tar -zcvf "pojt-${{ steps.get-version.outputs.version }}-linux-arm64.tar.gz" pojt
          GOOS=linux GOARCH=loong64 go build -o pojt
          tar -zcvf "pojt-${{ steps.get-version.outputs.version }}-linux-loong64.tar.gz" pojt
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          tag_name: ${{github.ref}}
          files: |
            pojt-*.tar.gz
